name: Update Dataset

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight (adjust as needed)
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-dataset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Check for changes
        run: |
          git fetch
          git diff --exit-code agenda_app/shiftslots.xlsx || echo "File has changed."  # Updated path

      - name: Commit and push changes
        if: ${{ success() }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add agenda_app/shiftslots.xlsx  # Updated path
          git commit -m 'Update shiftslots dataset'  # Updated commit message
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: No changes found
        if: failure()  # If no changes, this step runs
        run: echo "No changes detected, skipping commit."
