name: Update Dataset

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight (adjust as needed)
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-dataset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for changes
        id: check_changes
        run: |
          git fetch
          git diff --quiet shiftslots.xlsx || echo "File has changed."
        continue-on-error: true  # Allow the next step to run even if no changes found

      - name: Commit and push changes
        if: steps.check_changes.outcome == 'success'  # Proceed if changes detected
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add shiftslots.xlsx  # Updated path
          git commit -m 'Update shiftslots dataset'  # Updated commit message
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: No changes found
        if: steps.check_changes.outcome != 'success'  # If no changes, this step runs
        run: echo "No changes detected, skipping commit."
